version: '3.7'

services:
    consul:
        image: consul:latest
        container_name: consul
        hostname: consul
        restart: unless-stopped
        ports:
          - 8500:8500
        networks:
          - mservicenet
        # network_mode: host
        volumes:
          - consul:/consul/data
    
    fabio:
        image: fabiolb/fabio:latest
        container_name: fabio
        hostname: fabio
        restart: unless-stopped
        environment:
        - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
        networks:
        - mservicenet        
        ports:
        - 9998:9998
        - 9999:9999
    
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        container_name: es01
        restart: unless-stopped
        environment:
          - node.name=es01
          - cluster.name=es-docker-cluster
          - discovery.seed_hosts=es02,es03
          - cluster.initial_master_nodes=es01,es02,es03
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - data01:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
        networks:
          - elastic
    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        container_name: es02
        restart: unless-stopped
        environment:
          - node.name=es02
          - cluster.name=es-docker-cluster
          - discovery.seed_hosts=es01,es03
          - cluster.initial_master_nodes=es01,es02,es03
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - data02:/usr/share/elasticsearch/data
        networks:
          - elastic
    es03:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        container_name: es03
        restart: unless-stopped
        environment:
          - node.name=es03
          - cluster.name=es-docker-cluster
          - discovery.seed_hosts=es01,es02
          - cluster.initial_master_nodes=es01,es02,es03
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - data03:/usr/share/elasticsearch/data
        networks:
          - elastic

networks:
    mservicenet:
        name: mservice-network
    elastic:
        driver: bridge

          
volumes:
    consul:
      driver: local
    data01:
      driver: local
    data02:
      driver: local
    data03:
      driver: local
